version: '3.1'

services:
  db:
    image: postgres:13
    container_name: postgres_reservation_db
    environment:
      POSTGRES_DB: 'reservation_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'maslo'
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
